### ISSUE TITLE
Fictitious Co-Play implementation

### ISSUE THREAD

**Issue by cuijiaxun** [liyang619/COLE-Platform#3]
Hi, I am interested in your implementation of fictitious co-play in this repo, but I had a hard time finding it. Could you leave a pointer for that?

Or is it this one? (Does not look like the algorithm described in the FCP paper though)
https://github.com/liyang619/COLE-Platform/blob/COLE_training/human_aware_rl/pbt_original/fcp.py

**Comment by Bluixe** [comment]
Thanks for your question. I'm sorry that I missed this issue these days.
I think you may need to checkout to the baseline_training branch and following the README as:
`FCP`:
```
bash experiments/train_population.sh
bash experiments/fcp_train.sh
```
I hope this can be helpful.
